"""Off-policy multi-step prediction: importance sampling, control variates, Tree Backup,
Q(sigma), and the trace methods Q^pi(lambda), per-decision IS(lambda), TB(lambda), Retrace(lambda).

Chapter 06, Sections 4-7 and 14. Task: estimate q_pi on the slippery 15-state chain
(chain_mdp.py, gamma = 0.95) from episodes generated by a *different* behaviour
policy b. Error = RMS over the 30 (state, action) pairs against the exact q_pi.
Q starts at 0.

Part A, n-step methods (pi(right) = 0.9, b(right) = 0.5), all updating
Q(S_tau, A_tau) once its n-step window is complete:
  * naive:  uncorrected n-step Expected SARSA return (Eq. 6.7)
            R_{t+1} + ... + gamma^{n-1} R_{t+n} + gamma^n Vbar(S_{t+n})        (biased towards q_b)
  * IS:     the same return, update weighted by rho_{t+1:t+n-1}           (Eq. 6.10)
  * Q-corr: the recursion (6.14) with c = 1: Q-function corrections, no ratios
            (the n-step form of Harutyunyan et al.'s Q^pi(lambda) idea, Section 14)
  * CV:     per-decision IS with control variates                        (Eq. 6.12)
  * TB:     n-step Tree Backup                                            (Eq. 6.13)
  * Q(0.5): n-step Q(sigma) with sigma = 0.5                              (Eq. 6.15)
Q-corr, CV, TB and Q(sigma) all use the recursion (Eq. 6.14)
  G_{t:h} = R_{t+1} + gamma [ Vbar(S_{t+1}) + c_{t+1} (G_{t+1:h} - Q(S_{t+1}, A_{t+1})) ]
with c = 1, c = rho, c = pi(A|S) and c = sigma rho + (1 - sigma) pi(A|S) respectively.
Note that c = 1 is NOT the naive return: unrolling (6.14) with c = 1 gives the naive
return plus the terms gamma^{k-t} [Vbar(S_k) - Q(S_k, A_k)], k = t+1..h-1, which have
zero mean under pi and are exactly what removes the bias towards b.

Part B, trace methods with expected-SARSA TD errors and z <- gamma c_t z + e(S_t, A_t):
  Q^pi(lambda): c = lambda;  IS(lambda): c = lambda rho;  TB(lambda): c = lambda pi(A|S);
  Retrace(lambda): c = lambda min(1, rho)                                 (Section 14)
in two settings: "far" (pi(right) = 0.9, b(right) = 0.5) and "near" (pi(right) = 0.6, b = 0.5).

Every configuration is run for a grid of step sizes in parallel (Q has shape
(n_alpha, 17, 2)); all configurations share the same behaviour episodes. We report,
at the best alpha, the RMS error averaged over all episodes (area under the learning
curve) and the final RMS error (mean over the last 10 episodes).

Outputs (full mode): figures/off_policy_traces.png

Run:  python code/ch06_n_step_and_eligibility_traces/off_policy_traces.py [--quick]
"""
from __future__ import annotations

import argparse
import os
import time

os.environ.setdefault("OMP_NUM_THREADS", "1")   # one CPU thread (shared machine)
import numpy as np  # noqa: E402

import chain_mdp as cm  # noqa: E402

FIG_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "figures")
GAMMA = cm.GAMMA


def vbar(Q, pi, s):
    """Expected action value under pi at state s, for every alpha: shape (n_alpha,)."""
    return Q[:, s, :] @ pi[s]


# ---------------------------------------------------------------------------- Part A: n-step methods
def n_step_episode(Q, S, A, R, n, alphas, pi, b, method, sigma=0.5):
    """One episode of an off-policy n-step method, updating Q (n_alpha, 17, 2) in place."""
    T = len(R)
    rho = pi[S[:-1], A] / b[S[:-1], A]               # rho_t, t = 0..T-1
    p_act = pi[S[:-1], A]                             # pi(A_t | S_t)
    c = {"qcorr": np.ones_like(rho), "cv": rho, "tb": p_act,
         "qsigma": sigma * rho + (1 - sigma) * p_act}.get(method)
    disc = GAMMA ** np.arange(n)
    for t in range(T + n - 1):
        tau = t - n + 1
        if tau < 0:
            continue
        h = min(tau + n, T)                           # horizon of the return
        s, a = S[tau], A[tau]
        if method in ("naive", "is"):
            G = disc[: h - tau] @ R[tau:h]
            if h < T:
                G = G + GAMMA ** n * vbar(Q, pi, S[h])
            w = np.prod(rho[tau + 1: h]) if method == "is" else 1.0   # rho_{tau+1 : h-1}
            Q[:, s, a] += alphas * w * (G - Q[:, s, a])
        else:
            G = R[h - 1] + GAMMA * vbar(Q, pi, S[h])  # G_{h-1:h}; Vbar(terminal) = 0
            for k in range(h - 2, tau - 1, -1):       # G_{k:h} from G_{k+1:h}
                s1, a1 = S[k + 1], A[k + 1]
                G = R[k] + GAMMA * (vbar(Q, pi, s1) + c[k + 1] * (G - Q[:, s1, a1]))
            Q[:, s, a] += alphas * (G - Q[:, s, a])


# ---------------------------------------------------------------------------- Part B: trace methods
def trace_episode(Q, S, A, R, lam, alphas, pi, b, method):
    """Online backward view with expected-SARSA TD errors and trace coefficient c_t."""
    T = len(R)
    rho = pi[S[:-1], A] / b[S[:-1], A]
    c = {"qpi": np.full(T, lam), "is": lam * rho, "tb": lam * pi[S[:-1], A],
         "retrace": lam * np.minimum(1.0, rho)}[method]
    z = np.zeros(Q.shape[1:])                          # traces do not depend on alpha
    for t in range(T):
        s, a, s1 = S[t], A[t], S[t + 1]
        delta = R[t] + GAMMA * vbar(Q, pi, s1) - Q[:, s, a]
        z *= GAMMA * c[t]
        z[s, a] += 1.0
        Q += (alphas * delta)[:, None, None] * z[None]


def evaluate(update, episodes, alphas, q_true):
    """Run `update(Q, S, A, R)` over all runs/episodes.
    Returns err (n_runs, n_alpha, n_episodes): RMS error after every episode."""
    n_runs, n_eps = len(episodes), len(episodes[0])
    err = np.zeros((n_runs, len(alphas), n_eps))
    with np.errstate(over="ignore", invalid="ignore"):
        for i, run_eps in enumerate(episodes):
            Q = np.zeros((len(alphas),) + q_true.shape)
            for k, (S, A, R) in enumerate(run_eps):
                update(Q, S, A, R)
                err[i, :, k] = cm.rms_q_error(Q, q_true)
    err[~np.isfinite(err)] = np.inf
    return err


def summarize(err, alphas):
    """Best alpha by mean error over all episodes (with its standard error over runs),
    the final error (last 10 episodes) at that alpha, the lowest final error over alpha,
    and how many step sizes diverged (non-finite values)."""
    auc_runs = err.mean(axis=2)                       # (n_runs, n_alpha)
    auc = auc_runs.mean(axis=0)
    final = err[:, :, -10:].mean(axis=(0, 2))
    j = int(np.argmin(auc))
    se = auc_runs[:, j].std(ddof=1) / np.sqrt(err.shape[0])
    return dict(alpha=alphas[j], auc=auc[j], se=se, final=final[j], best_final=final.min(),
                n_div=int((~np.isfinite(auc)).sum()))


def make_episodes(rng, b, n_runs, n_eps):
    return [[cm.generate_episode(rng, b) for _ in range(n_eps)] for _ in range(n_runs)]


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--quick", action="store_true", help="smoke test, no figures")
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()
    if args.quick:
        n_runs, n_eps = 3, 20
        ns, lams = [1, 4, 16], [0.0, 0.9, 1.0]
        alphas = np.array([0.05, 0.2, 0.5])
    else:
        n_runs, n_eps = 30, 50
        ns, lams = [1, 2, 4, 8, 16], [0.0, 0.5, 0.8, 0.9, 0.95, 1.0]
        alphas = np.array([0.01, 0.02, 0.05, 0.1, 0.2, 0.3, 0.5, 0.7, 1.0])
    settings = {"far": (0.9, 0.5), "near": (0.6, 0.5)}
    print(f"Off-policy prediction of q_pi on the {cm.N}-state chain | seed={args.seed} gamma={GAMMA} "
          f"runs={n_runs} episodes={n_eps}")
    print(f"settings (pi(right), b(right)): {settings}\nalpha in {alphas.tolist()}")
    t0 = time.time()
    rng = np.random.default_rng(args.seed)

    data = {}
    for name, (p_pi, p_b) in settings.items():
        pi, b = cm.policy(p_pi), cm.policy(p_b)
        q_true = cm.exact_q(pi)
        q_b = cm.exact_q(b)
        eps = make_episodes(rng, b, n_runs, n_eps)
        mean_T = np.mean([len(e[2]) for run in eps for e in run])
        data[name] = (pi, b, q_true, eps)
        print(f"\n[{name}] pi(right)={p_pi}, b(right)={p_b}: RMS of q_pi = {cm.rms_q_error(np.zeros_like(q_true), q_true):.4f}, "
              f"RMS(q_b - q_pi) = {cm.rms_q_error(q_b, q_true):.4f}, mean episode length {mean_T:.1f}")
        ratios = (pi / np.where(b > 0, b, 1))[1]
        Eb = lambda c: float(b[1] @ c)                                  # E_b[c(A)]  # noqa: E731
        print(f"  E_b[c]/lambda per step:  Q^pi 1.000   IS {Eb(ratios):.3f}   TB {Eb(pi[1]):.3f}   "
              f"Retrace {Eb(np.minimum(1, ratios)):.3f};   E_b[rho^2] = {Eb(ratios ** 2):.3f}")

    # ---- Part A
    pi, b, q_true, eps = data["far"]
    methods_A = {"naive (no correction)": "naive", "IS": "is", "Q-corrected, c=1": "qcorr",
                 "per-decision CV": "cv", "Tree Backup": "tb", "Q(σ=0.5)": "qsigma"}
    resA = {m: [] for m in methods_A}
    print("\nPart A: n-step methods, far setting. At the alpha minimising the mean RMS over all episodes:")
    print("  method                   n   alpha   mean RMS (s.e.)    final RMS  (best final over alpha)  #alpha diverged")
    for label, m in methods_A.items():
        for n in ns:
            err = evaluate(lambda Q, S, A, R: n_step_episode(Q, S, A, R, n, alphas, pi, b, m),
                           eps, alphas, q_true)
            r = summarize(err, alphas)
            resA[label].append(r)
            print(f"  {label:22s} {n:3d}   {r['alpha']:5.2f}   {r['auc']:.4f} ({r['se']:.4f})   "
                  f"{r['final']:9.4f}  ({r['best_final']:.4f})                 {r['n_div']}")
    print(f"  [Part A done at {time.time() - t0:.1f} s]")

    # ---- Part B
    methods_B = {r"$Q^\pi(\lambda)$, $c=\lambda$": "qpi",
                 r"IS($\lambda$), $c=\lambda\rho$": "is",
                 r"TB($\lambda$), $c=\lambda\pi(A|S)$": "tb",
                 r"Retrace($\lambda$), $c=\lambda\min(1,\rho)$": "retrace"}
    resB = {}
    for setting in settings:
        pi, b, q_true, eps = data[setting]
        resB[setting] = {m: [] for m in methods_B}
        print(f"\nPart B: trace methods, {setting} setting (best alpha by mean RMS):")
        print("  method                       lambda  alpha   mean RMS (s.e.)    final RMS  #alpha diverged")
        for label, m in methods_B.items():
            for lam in lams:
                err = evaluate(lambda Q, S, A, R: trace_episode(Q, S, A, R, lam, alphas, pi, b, m),
                               eps, alphas, q_true)
                r = summarize(err, alphas)
                resB[setting][label].append(r)
                print(f"  {m:27s} {lam:6.2f}   {r['alpha']:5.2f}   {r['auc']:.4f} ({r['se']:.4f})   "
                      f"{r['final']:9.4f}   {r['n_div']}")
    print(f"\nelapsed {time.time() - t0:.1f} s")

    if args.quick:
        return
    from plot_style import setup, C
    plt = setup()
    os.makedirs(FIG_DIR, exist_ok=True)
    fig, axes = plt.subplots(2, 2, figsize=(12, 8.4))
    # One colour per method *family* across both rows: c = 1 and Q^pi(lambda) share a colour,
    # as do IS and IS(lambda), and Tree Backup and TB(lambda).
    style_A = {"naive": (C[7], "o"), "is": (C[1], "s"), "qcorr": (C[0], "^"), "cv": (C[4], "D"),
               "tb": (C[2], "v"), "qsigma": (C[5], "P")}
    style_B = {"qpi": (C[0], "^"), "is": (C[1], "s"), "tb": (C[2], "v"), "retrace": (C[3], "X")}
    for col, key in enumerate(["auc", "best_final"]):
        ax = axes[0, col]
        for label, rs in resA.items():
            col_, mk = style_A[methods_A[label]]
            if key == "auc":
                ax.errorbar(ns, [r[key] for r in rs], yerr=[r["se"] for r in rs], color=col_,
                            marker=mk, capsize=2, label=label)
            else:
                ax.plot(ns, [r[key] for r in rs], color=col_, marker=mk, label=label)
        ax.set_xscale("log", base=2)
        ax.set_xticks(ns); ax.set_xticklabels([str(n) for n in ns])
        ax.set_xlabel("n")
        ax.set_ylabel("RMS error of Q vs $q_\\pi$")
        ax.set_title(f"(a) n-step: mean RMS over {n_eps} episodes (best α, ±1 s.e.)" if key == "auc" else
                     f"(b) n-step: lowest final RMS (episodes {n_eps - 9}-{n_eps}) over α", fontsize=10)
        ax.legend(fontsize=8)
    for col, setting in enumerate(settings):
        ax = axes[1, col]
        for label, rs in resB[setting].items():
            col_, mk = style_B[methods_B[label]]
            ax.errorbar(lams, [r["auc"] for r in rs], yerr=[r["se"] for r in rs], color=col_,
                        marker=mk, capsize=2, label=label)
        p_pi, p_b = settings[setting]
        ax.set_xlabel(r"$\lambda$")
        ax.set_ylabel(f"mean RMS error over {n_eps} episodes (best α)")
        ax.set_title(f"({'c' if col == 0 else 'd'}) trace methods, {setting}: π(right)={p_pi}, b(right)={p_b}",
                     fontsize=10)
        ax.legend(fontsize=8)
    for ax in axes.flat:
        ax.set_ylim(bottom=0)
    fig.suptitle(f"Off-policy evaluation of $q_\\pi$ on the slippery {cm.N}-state chain ({n_runs} runs); "
                 "top row: π(right)=0.9, b(right)=0.5", y=0.995)
    fig.tight_layout()
    path = os.path.join(FIG_DIR, "off_policy_traces.png")
    fig.savefig(path)
    plt.close(fig)
    print(f"saved {path}")


if __name__ == "__main__":
    main()
