"""Off-policy prediction by importance sampling on one Blackjack state (Sec. 6.5; S&B Example 5.4).

State: player holds an ace and a deuce (sum 13, usable ace), dealer shows a deuce.
Target policy pi: stick only on 20 or 21. Behavior policy b: hit or stick with prob 1/2.
Each episode starts in that state and is generated by b. Its importance-sampling ratio is

    rho = prod_t pi(A_t|S_t) / b(A_t|S_t) = 2^D  if all D actions agree with pi, else 0
    (D = number of decisions in the episode),

and the two estimators after n episodes are

    ordinary IS : V_n = sum_i rho_i G_i / n
    weighted IS : V_n = sum_i rho_i G_i / sum_i rho_i     (0 while the denominator is 0).

S&B report the true value as about -0.27726 (an average over 1e8 episodes). We compute it
exactly with blackjack.solve, together with the exact per-episode variance of rho*G, which
gives the exact MSE curve of ordinary IS: E_b[(rho G)^2] - v^2, divided by n. The same
recursion gives the exact one-episode MSE of weighted IS, P_b(rho > 0), and the fourth moment
of rho*G - v, from which we get the standard error of the simulated MSE at n = 1.

The card shoe and the behaviour policy use two independent random streams spawned from one
SeedSequence, so the 1,000 runs are genuinely independent replicates.

    python code/ch04_monte_carlo/off_policy_is_blackjack.py [--quick]
"""
import argparse
import os
import time
from math import comb

import numpy as np
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

from blackjack import (Blackjack, HIT, STICK, CARD_VALUES, CARD_PROBS, dealer_outcomes,
                       hand_value, solve, stick_on_20_policy)

HERE = os.path.dirname(os.path.abspath(__file__))
START = (13, 2, 1)            # (player sum, dealer showing, usable ace)


def target_pi(obs):
    return HIT if obs[0] < 20 else STICK


def run_episode_with_b(env, rng_buf):
    """One episode from START under the random behavior policy. Returns (rho, G)."""
    obs = env.reset(start=START)
    rho, done, r = 1.0, False, 0
    while not done:
        a = rng_buf.pop()
        # pi is deterministic: pi(a|s) is 1 for its action and 0 otherwise; b(a|s) = 1/2.
        rho *= (2.0 if a == target_pi(obs) else 0.0)
        obs, r, done = env.step(a)
    return rho, r                # gamma = 1 and all earlier rewards are 0, so G = final reward


def stick_outcomes(player_sum, showing):
    """(P(win), P(draw), P(lose)) when a non-natural hand of `player_sum` sticks."""
    dist, _ = dealer_outcomes(showing)
    totals = np.arange(17, 22)
    win = dist[5] + dist[:5][totals < player_sum].sum()
    draw = dist[:5][totals == player_sum].sum()
    return win, draw, 1 - win - draw


def exact_b_moment(f, j=2, raw=3, ace=True, showing=2):
    """E_b[rho^j f(G); rho > 0] = E_pi[(2^(j-1))^D f(G)]  (D = number of decisions).

    Derivation (Sec. 6.5): on a pi-consistent trajectory rho = 2^D and P_b = P_pi / rho, so
    sum_tau P_b(tau) rho^j f(G) = sum_tau P_pi(tau) rho^(j-1) f(G). Trajectories with rho = 0
    are excluded, so j = 0 with f = 1 gives P_b(rho > 0). Each decision of pi contributes the
    factor 2^(j-1); we recurse over the player's hand exactly as the solver does."""
    factor = 2.0 ** (j - 1)
    s, _ = hand_value(raw, ace)
    if s >= 20:                                   # pi sticks
        w, d, l = stick_outcomes(s, showing)
        return factor * (w * f(1) + d * f(0) + l * f(-1))
    total = 0.0
    for c, p in zip(CARD_VALUES.tolist(), CARD_PROBS.tolist()):
        if raw + c > 21:
            total += p * f(-1)                    # bust: no further decisions
        else:
            total += p * exact_b_moment(f, j, raw + c, ace or c == 1, showing)
    return factor * total


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--quick", action="store_true")
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()
    runs = 20 if args.quick else 1000
    n_ep = 2_000 if args.quick else 10_000
    print(f"Off-policy IS on Blackjack state {START} | seed={args.seed} runs={runs} "
          f"episodes/run={n_ep:,} b=uniform random, pi=stick on 20/21")
    v = solve(stick_on_20_policy())["V"][START[0] - 12, START[1] - 1, START[2]]
    v_check = exact_b_moment(lambda g: g, 1)              # E_b[rho G] must equal v (Prop. 6.1)
    var_o = exact_b_moment(lambda g: g * g, 2) - v * v    # Var_b[rho G]
    m_w = exact_b_moment(lambda g: (g - v) ** 2, 2)       # E_b[rho^2 (G - v)^2]
    p_pos = exact_b_moment(lambda g: 1.0, 0)              # P_b(rho > 0)
    # One episode of weighted IS outputs G if rho > 0 and the convention 0 otherwise.
    mse_w1 = exact_b_moment(lambda g: (g - v) ** 2, 0) + (1 - p_pos) * v * v
    # Fourth central moment of rho G - v: binomial expansion, E_b[(rho G)^0] = 1.
    m4 = v ** 4 + sum(comb(4, j) * (-v) ** (4 - j) * exact_b_moment(lambda g, j=j: g ** j, j)
                      for j in range(1, 5))
    print(f"exact v_pi(s) = {v:.6f}   (check E_b[rho G] = {v_check:.6f}; S&B: -0.27726 from 1e8 "
          f"episodes)")
    print(f"exact P_b(rho > 0) = {p_pos:.4f}")
    print(f"exact per-episode variance of rho*G under b: {var_o:.4f}  -> ordinary IS MSE = "
          f"{var_o:.4f}/n;  weighted IS asymptotic MSE ~ E_b[rho^2 (G-v)^2]/n = {m_w:.4f}/n")
    print(f"exact MSE after one episode: ordinary {var_o:.4f}, weighted {mse_w1:.4f} "
          f"(ratio {var_o / mse_w1:.1f})")
    print(f"exact E_b[(rho G - v)^4] = {m4:.1f} -> standard error of a {runs}-run estimate of the "
          f"n=1 ordinary-IS MSE: {np.sqrt((m4 - var_o ** 2) / runs):.3f}")

    t0 = time.time()
    # Two independent streams: one for the cards, one for the behaviour policy's coin flips.
    # (Seeding both with the same integer would make them emit the same PCG64 words.)
    env_ss, b_ss = np.random.SeedSequence(args.seed).spawn(2)
    env = Blackjack(env_ss)
    rng = np.random.default_rng(b_ss)
    ordinary = np.empty((runs, n_ep))
    weighted = np.empty((runs, n_ep))
    nonzero = 0
    for k in range(runs):
        buf = rng.integers(0, 2, size=8 * n_ep).tolist()   # behavior actions (enough for any run)
        rho_g = np.empty(n_ep)
        rho = np.empty(n_ep)
        for i in range(n_ep):
            rho[i], g = run_episode_with_b(env, buf)
            rho_g[i] = rho[i] * g
        nonzero += (rho > 0).sum()
        num, den = np.cumsum(rho_g), np.cumsum(rho)
        ordinary[k] = num / np.arange(1, n_ep + 1)
        with np.errstate(invalid="ignore", divide="ignore"):
            weighted[k] = np.where(den > 0, num / den, 0.0)
    sq_o, sq_w = (ordinary - v) ** 2, (weighted - v) ** 2
    mse_o, mse_w = sq_o.mean(0), sq_w.mean(0)
    se_o, se_w = sq_o.std(0, ddof=1) / np.sqrt(runs), sq_w.std(0, ddof=1) / np.sqrt(runs)
    print(f"simulation: {time.time() - t0:.1f}s; fraction of episodes with rho > 0: "
          f"{nonzero / (runs * n_ep):.4f} (exact {p_pos:.4f})")
    print("\n  episodes |  MSE ordinary +- s.e.  (exact)  |  MSE weighted +- s.e. | bias weighted")
    for n in (1, 2, 5, 10, 20, 50, 100, 200, 500, 1000, 2000, 5000, 10000):
        if n <= n_ep:
            print(f"  {n:8,d} | {mse_o[n - 1]:9.4f} +- {se_o[n - 1]:7.4f} ({var_o / n:8.4f}) | "
                  f"{mse_w[n - 1]:9.4f} +- {se_w[n - 1]:7.4f} | {weighted[:, n - 1].mean() - v:+.4f}")
    print(f"ratio MSE_ordinary / MSE_weighted at n = {n_ep}: {mse_o[-1] / mse_w[-1]:.2f}")
    print("(s.e. = sample standard error over runs; for heavy-tailed rho*G it is itself noisy)")
    print(f"total elapsed {time.time() - t0:.1f}s")

    if args.quick:
        return
    os.makedirs(os.path.join(HERE, "figures"), exist_ok=True)
    x = np.arange(1, n_ep + 1)
    fig, axes = plt.subplots(1, 2, figsize=(12, 4.3))
    for ax, logy in zip(axes, (False, True)):
        ax.plot(x, mse_o, color="C3", label="ordinary importance sampling")
        ax.plot(x, mse_w, color="C2", label="weighted importance sampling")
        ax.plot(x, var_o / x, "C3:", lw=1, label="ordinary IS, exact Var/n")
        ax.plot(x, m_w / x, "C2:", lw=1, label="weighted IS, asymptotic (delta method)")
        ax.set_xscale("log")
        if logy:
            ax.set_yscale("log")
            ax.set_title("same data, log-log axes")
        else:
            ax.set_ylim(0, 5)
            ax.set_title(f"Off-policy estimation of v(13, dealer 2, usable ace) = {v:.5f}")
        ax.set_xlabel("episodes (log scale)")
        ax.set_ylabel(f"mean squared error (average over {runs} runs)")
        ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(os.path.join(HERE, "figures", "blackjack_off_policy_is.png"), dpi=110)
    print("saved figures/blackjack_off_policy_is.png")


if __name__ == "__main__":
    main()
