"""Baird's counterexample and the deadly triad (Chapter 08, Sections 13-17;
cf. Sutton & Barto Figs 11.1, 11.2, 11.5, 11.6).

MDP: 7 states. The "dashed" action jumps to one of the six upper states uniformly;
the "solid" action jumps to the lower (7th) state. All rewards are 0, gamma = 0.99,
so v_pi = 0 for every policy.  Behaviour b: dashed w.p. 6/7, solid w.p. 1/7 (so the
next state is uniform and d_b is uniform). Target pi: always solid.
Importance ratio rho = pi/b is 0 for dashed and 7 for solid.

Features (8 weights): upper state i -> v_hat = 2 w_i + w_8; lower state -> w_7 + 2 w_8.
These 7 feature vectors are linearly independent, so *every* value function is
representable, including v_pi = 0 (w = 0). Divergence is therefore not caused by a
lack of representational power -- it is caused by the update dynamics.

Experiments
  1. semi-gradient off-policy TD(0) (sample) and semi-gradient DP (expected): diverge;
  2. TDC (sample + expected), GTD2 (expected): PBE -> 0, stable;
  3. one-step emphatic TD (expected: converges; sample: show its variance);
  4. the deadly triad: remove each of {function approximation, bootstrapping,
     off-policy} from the expected semi-gradient TD update and it becomes stable.

Run:  python code/ch08_function_approximation/baird_counterexample.py [--quick]
"""
from __future__ import annotations

import os

os.environ.setdefault("OMP_NUM_THREADS", "1")       # one BLAS thread: the machine is shared
os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")

import argparse

import numpy as np

FIG_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "figures")

N_S, D_W = 7, 8
GAMMA = 0.99
LOWER = 6
DASHED, SOLID = 0, 1
B_PROB = np.array([6 / 7, 1 / 7])        # behaviour policy
PI_PROB = np.array([0.0, 1.0])           # target policy
RHO = PI_PROB / B_PROB                   # [0, 7]
W0 = np.array([1, 1, 1, 1, 1, 1, 10, 1], dtype=float)

X = np.zeros((N_S, D_W))
for i in range(6):
    X[i, i], X[i, 7] = 2.0, 1.0
X[LOWER, 6], X[LOWER, 7] = 1.0, 2.0

# Model quantities ---------------------------------------------------------- #
P_DASHED = np.zeros((N_S, N_S)); P_DASHED[:, :6] = 1 / 6
P_SOLID = np.zeros((N_S, N_S)); P_SOLID[:, LOWER] = 1.0
P_PI = P_SOLID                                        # target policy transition matrix
P_B = B_PROB[0] * P_DASHED + B_PROB[1] * P_SOLID      # = uniform
D_B = np.full(N_S, 1 / N_S)                           # stationary distribution of b
R_PI = np.zeros(N_S)                                  # expected reward under pi
D = np.diag(D_B)


def sqrt_ve(w):
    """sqrt(VE) under the behaviour distribution; v_pi = 0."""
    return float(np.sqrt(D_B @ (X @ w) ** 2))


def sqrt_pbe(w):
    """sqrt(PBE) = sqrt( E[rho delta x]^T E[x x^T]^+ E[rho delta x] )  (Section 15)."""
    delta_bar = R_PI + GAMMA * P_PI @ X @ w - X @ w      # Bellman error vector (target pi)
    g = X.T @ D @ delta_bar
    return float(np.sqrt(max(g @ np.linalg.pinv(X.T @ D @ X) @ g, 0.0)))


# --------------------------------------------------------------------------- #
# Sample-based algorithms: follow b, learn about pi
# --------------------------------------------------------------------------- #
def simulate(n_steps, rng):
    """States S_0..S_n and actions A_0..A_{n-1} generated by the behaviour policy."""
    S = np.empty(n_steps + 1, dtype=int)
    A = (rng.random(n_steps) < B_PROB[SOLID]).astype(int)       # 1 = solid
    S[0] = rng.integers(N_S)
    upper = rng.integers(6, size=n_steps)
    for t in range(n_steps):
        S[t + 1] = LOWER if A[t] == SOLID else upper[t]
    return S, A


def semi_gradient_td(S, A, alpha=0.01):
    """Off-policy semi-gradient TD(0): w <- w + alpha rho_t delta_t x_t (Section 13.1)."""
    w = W0.copy()
    hist = [w.copy()]
    for t in range(len(A)):
        x, x2, rho = X[S[t]], X[S[t + 1]], RHO[A[t]]
        delta = 0.0 + GAMMA * x2 @ w - x @ w
        w = w + alpha * rho * delta * x
        hist.append(w.copy())
    return np.array(hist)


def tdc(S, A, alpha=0.005, beta=0.05, gtd2=False):
    """TDC (a.k.a. GTD(0)) and GTD2 (Section 16)."""
    w, v = W0.copy(), np.zeros(D_W)
    hist = [w.copy()]
    for t in range(len(A)):
        x, x2, rho = X[S[t]], X[S[t + 1]], RHO[A[t]]
        delta = 0.0 + GAMMA * x2 @ w - x @ w
        xv = x @ v
        if gtd2:
            w = w + alpha * rho * (x - GAMMA * x2) * xv
        else:
            w = w + alpha * rho * (delta * x - GAMMA * x2 * xv)
        v = v + beta * rho * (delta - xv) * x
        hist.append(w.copy())
    return np.array(hist)


def emphatic_td(S, A, alpha=0.03, interest=1.0):
    """One-step emphatic TD (Section 17 box): M_t = gamma rho_{t-1} M_{t-1} + i_t (interest i_t),
    w <- w + alpha M_t rho_t delta_t x_t."""
    w = W0.copy()
    M, rho_prev = 0.0, 0.0
    hist, Ms = [w.copy()], []
    for t in range(len(A)):
        x, x2, rho = X[S[t]], X[S[t + 1]], RHO[A[t]]
        M = GAMMA * rho_prev * M + interest
        delta = 0.0 + GAMMA * x2 @ w - x @ w
        w = w + alpha * M * rho * delta * x
        rho_prev = rho
        hist.append(w.copy())
        Ms.append(M)
    return np.array(hist), np.array(Ms)


# --------------------------------------------------------------------------- #
# Expected ("DP") versions: average the update over s ~ d, a ~ b, s' ~ p
# --------------------------------------------------------------------------- #
def expected_semi_gradient(n_sweeps, alpha=0.01, Xf=X, P=P_PI, d=D_B, w0=None, target=None):
    """w <- w + alpha * sum_s d(s) [E_pi(R + gamma v_hat(S')) - v_hat(s)] x(s).
    With target='true', the bootstrapped target is replaced by v_pi (= 0): gradient
    descent on VE, i.e. no bootstrapping."""
    w = (W0.copy() if w0 is None else w0.copy())
    Dm = np.diag(d)
    hist = [w.copy()]
    for _ in range(n_sweeps):
        if target == "true":
            delta_bar = 0.0 - Xf @ w                          # v_pi = 0
        else:
            delta_bar = R_PI + GAMMA * P @ Xf @ w - Xf @ w
        w = w + alpha * Xf.T @ Dm @ delta_bar
        hist.append(w.copy())
    return np.array(hist)


def expected_tdc(n_sweeps, alpha=0.005, beta=0.05, gtd2=False):
    C = X.T @ D @ X                          # E[x x^T]
    Cn = (P_PI @ X).T @ D @ X                # E[rho x' x^T]
    w, v = W0.copy(), np.zeros(D_W)
    hist = [w.copy()]
    for _ in range(n_sweeps):
        g = X.T @ D @ (R_PI + GAMMA * P_PI @ X @ w - X @ w)    # E[rho delta x]
        if gtd2:
            w = w + alpha * (C - GAMMA * Cn) @ v               # E[rho (x - gamma x') x^T] v
        else:
            w = w + alpha * (g - GAMMA * Cn @ v)
        v = v + beta * (g - C @ v)
        hist.append(w.copy())
    return np.array(hist)


def emphatic_weights(interest=1.0):
    """m = (I - gamma P_pi^T)^{-1} (d_b * i): expected emphasis per state (lambda = 0)."""
    return np.linalg.solve(np.eye(N_S) - GAMMA * P_PI.T, D_B * interest)


def expected_etd(n_sweeps, alpha=0.03):
    m = emphatic_weights()
    w = W0.copy()
    hist = [w.copy()]
    for _ in range(n_sweeps):
        w = w + alpha * X.T @ np.diag(m) @ (R_PI + GAMMA * P_PI @ X @ w - X @ w)
        hist.append(w.copy())
    return np.array(hist)


def key_matrix_eigs(Xf, d, P, bootstrap=True):
    """Eigenvalues that govern the expected update w += alpha (b - A w) (Section 5).
    A = X^T D (I - gamma P) X with bootstrapping, A = X^T D X without. We return the
    eigenvalues of the n x n matrix D (I - gamma P) X X^T, which equal the non-zero
    eigenvalues of A -- Baird's 8 weights for 7 states add one exact zero eigenvalue
    (a direction of w that does not change v_hat), which we leave out."""
    M = np.diag(d) @ (np.eye(len(d)) - GAMMA * P) if bootstrap else np.diag(d)
    return np.linalg.eigvals(M @ Xf @ Xf.T)


# --------------------------------------------------------------------------- #
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--quick", action="store_true", help="smoke test, no figures")
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()
    n = 200 if args.quick else 1000
    n_triad = 500 if args.quick else 5000
    n_long = 2000 if args.quick else 50_000
    rng = np.random.default_rng(args.seed)
    print(f"seed={args.seed} quick={args.quick} gamma={GAMMA} w0={W0.astype(int).tolist()}")
    print(f"steps/sweeps = {n}; alpha_TD=0.01, TDC alpha=0.005 beta=0.05, ETD alpha=0.03\n")

    eig = key_matrix_eigs(X, D_B, P_PI)
    print("A = X^T D_b (I - gamma P_pi) X: non-zero eigenvalues (real parts):",
          np.round(np.sort(eig.real), 4))
    S, A = simulate(n, rng)

    td_hist = semi_gradient_td(S, A)
    dp_hist = expected_semi_gradient(n)
    print(f"\n1. semi-gradient off-policy TD (sample): ||w|| {np.linalg.norm(W0):.1f} -> "
          f"{np.linalg.norm(td_hist[-1]):.1f} after {n} steps;  sqrtVE = {sqrt_ve(td_hist[-1]):.1f}")
    print(f"   semi-gradient DP (expected):          ||w|| {np.linalg.norm(W0):.1f} -> "
          f"{np.linalg.norm(dp_hist[-1]):.1f} after {n} sweeps; sqrtVE = {sqrt_ve(dp_hist[-1]):.1f}")

    tdc_hist = tdc(S, A)
    etdc_hist = expected_tdc(n)
    egtd2_hist = expected_tdc(n, gtd2=True)
    print(f"\n2. TDC (sample, {n} steps):     sqrtVE = {sqrt_ve(tdc_hist[-1]):.3f}, sqrtPBE = {sqrt_pbe(tdc_hist[-1]):.4f}")
    print(f"   TDC (expected, {n} sweeps):   sqrtVE = {sqrt_ve(etdc_hist[-1]):.3f}, sqrtPBE = {sqrt_pbe(etdc_hist[-1]):.4f}")
    print(f"   GTD2 (expected, {n} sweeps):  sqrtVE = {sqrt_ve(egtd2_hist[-1]):.3f}, sqrtPBE = {sqrt_pbe(egtd2_hist[-1]):.4f}")
    S_long, A_long = simulate(n_long, np.random.default_rng(args.seed + 1))
    long_tdc = tdc(S_long, A_long)
    long_etdc = expected_tdc(n_long)
    print(f"   expected TDC values after {n} sweeps: v_hat = {np.round(X @ etdc_hist[-1], 3).tolist()}")
    print(f"   longer: TDC sample {n_long} steps: sqrtVE = {sqrt_ve(long_tdc[-1]):.3f}, "
          f"sqrtPBE = {sqrt_pbe(long_tdc[-1]):.4f};  expected TDC {n_long} sweeps: "
          f"sqrtVE = {sqrt_ve(long_etdc[-1]):.4f}, sqrtPBE = {sqrt_pbe(long_etdc[-1]):.5f}")
    finals = []
    for k in range(10):
        Sk, Ak = simulate(n, np.random.default_rng(100 + k))
        hk = tdc(Sk, Ak)
        finals.append((sqrt_ve(hk[-1]), sqrt_pbe(hk[-1]), np.abs(hk).max()))
    finals = np.array(finals)
    print(f"   TDC sample over 10 seeds after {n} steps: sqrtVE in [{finals[:, 0].min():.2f}, {finals[:, 0].max():.2f}],"
          f" sqrtPBE in [{finals[:, 1].min():.3f}, {finals[:, 1].max():.3f}], max |w_i| ever = {finals[:, 2].max():.2f}")

    m = emphatic_weights()
    etd_hist = expected_etd(n)
    eig_etd = np.linalg.eigvals(np.diag(m) @ (np.eye(N_S) - GAMMA * P_PI) @ X @ X.T)
    print(f"\n3. emphasis m(s) = {np.round(m, 3).tolist()}")
    print(f"   ETD key matrix X^T M (I - gamma P_pi) X, non-zero eigenvalues (real parts): {np.round(np.sort(eig_etd.real), 4).tolist()}")
    print(f"   expected ETD after {n} sweeps: sqrtVE = {sqrt_ve(etd_hist[-1]):.4f}, ||w|| = {np.linalg.norm(etd_hist[-1]):.3f}")
    setd_hist, Ms = emphatic_td(S, A)
    print(f"   sample ETD after {n} steps: sqrtVE = {sqrt_ve(setd_hist[-1]):.3g}, max M_t = {Ms.max():.3g}, "
          f"max ||w|| = {np.linalg.norm(setd_hist, axis=1).max():.3g}")
    sv = []
    for k in range(10):
        Sk, Ak = simulate(n, np.random.default_rng(200 + k))
        hk, Mk = emphatic_td(Sk, Ak)
        sv.append((sqrt_ve(hk[-1]), Mk.max()))
    sv = np.array(sv)
    print(f"   sample ETD over 10 seeds: final sqrtVE ranges {sv[:, 0].min():.3g} .. {sv[:, 0].max():.3g},"
          f" max M_t ranges {sv[:, 1].min():.3g} .. {sv[:, 1].max():.3g}")

    # ---- 4. deadly triad: knock out one ingredient at a time (expected updates) ----
    X_tab = np.eye(N_S)                                       # tabular: no generalisation
    variants = {
        "all three (FA + bootstrapping + off-policy)": dict(),
        "no function approximation (tabular features)": dict(Xf=X_tab, w0=X @ W0),   # same initial v_hat
        "no bootstrapping (target = v_pi, i.e. MC in expectation)": dict(target="true"),
        "no off-policy (evaluate b itself under d_b)": dict(P=P_B),
    }
    triad = {}
    print("\n4. deadly triad, expected semi-gradient TD, alpha = 0.01 (v = 0 in every variant):")
    for name, kw in variants.items():
        h = expected_semi_gradient(n_triad, **kw)
        Xf = kw.get("Xf", X)
        # v = 0 for pi and for b, so max_s |v_hat(s)| is the max-norm value error; the tabular
        # expected update is a max-norm contraction, so this is the honest yardstick
        triad[name] = np.abs(h @ Xf.T).max(axis=1)
        P = kw.get("P", P_PI)
        ev = key_matrix_eigs(Xf, D_B, P, bootstrap=kw.get("target") != "true").real
        rve = np.sqrt(((h @ Xf.T) ** 2) @ D_B)
        print(f"   {name:58s}: min Re eig(A) = {ev.min():+.4f}; max_s|v_hat(s)| at start / after {n} / after"
              f" {n_triad} sweeps = {triad[name][0]:.3g} / {triad[name][n]:.3g} / {triad[name][-1]:.3g};"
              f" sqrtVE = {rve[0]:.3g} / {rve[n]:.3g} / {rve[-1]:.3g} (max over sweeps {rve.max():.3g})")

    if args.quick:
        return
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    os.makedirs(FIG_DIR, exist_ok=True)
    cols = plt.get_cmap("tab10")
    labels = [f"$w_{i + 1}$" for i in range(D_W)]

    def plot_w(ax, hist, title, xlabel):
        for i in range(D_W):
            ax.plot(hist[:, i], color=cols(i), lw=1.2, label=labels[i])
        ax.set_title(title, fontsize=10)
        ax.set_xlabel(xlabel)

    fig, axes = plt.subplots(1, 2, figsize=(12, 4.2))
    plot_w(axes[0], td_hist, "Semi-gradient off-policy TD(0)", "steps")
    plot_w(axes[1], dp_hist, "Semi-gradient DP (expected update)", "sweeps")
    axes[0].set_ylabel("weight value")
    axes[1].legend(ncol=2, fontsize=8)
    fig.suptitle(r"Baird's counterexample: divergence ($\gamma$=0.99, $\alpha$=0.01)")
    fig.tight_layout()
    fig.savefig(os.path.join(FIG_DIR, "baird_divergence.png"), dpi=110)

    fig, axes = plt.subplots(1, 3, figsize=(16, 4.4))
    for ax, hist, title, xl in [(axes[0], tdc_hist, "TDC (sample), α=0.005, β=0.05", "steps"),
                                (axes[1], etdc_hist, "Expected TDC", "sweeps"),
                                (axes[2], etd_hist, "Expected emphatic TD, α=0.03", "sweeps")]:
        plot_w(ax, hist, title, xl)
        ve = [sqrt_ve(w) for w in hist]
        ax.plot(ve, "k--", lw=2, label=r"$\sqrt{\overline{VE}}$")
        if ax is not axes[2]:
            pbe = [sqrt_pbe(w) for w in hist]
            ax.plot(pbe, "k:", lw=2, label=r"$\sqrt{\overline{PBE}}$")
    axes[0].set_ylabel("weight value / error")
    axes[1].legend(ncol=2, fontsize=8)
    axes[2].legend(ncol=2, fontsize=8)
    fig.suptitle("Baird's counterexample: gradient-TD (TDC) and emphatic TD remain stable")
    fig.tight_layout()
    fig.savefig(os.path.join(FIG_DIR, "baird_tdc_etd.png"), dpi=110)

    fig, ax = plt.subplots(figsize=(7.5, 4.3))
    for name, ve in triad.items():
        ax.semilogy(np.maximum(ve, 1e-12), label=name)
    ax.set_xlabel("sweeps (expected updates)")
    ax.set_ylabel(r"$\max_s |\hat v(s,\mathbf{w}) - v_\pi(s)|$ (log scale)")
    ax.set_title("Deadly triad: remove any one ingredient and the update is stable")
    ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(os.path.join(FIG_DIR, "baird_triad.png"), dpi=110)
    print(f"\nfigures saved to {FIG_DIR}")


if __name__ == "__main__":
    main()
