"""Ordinary vs weighted importance sampling, and the variance blow-up with horizon.

Chapter 00, Section 2.6. Setting (the worked example of Section 2.6):
  * two actions; behaviour policy b = (0.5, 0.5); target policy pi = (0.9, 0.1);
  * a step pays reward 1 if action 0 is taken, else 0;
  * an "episode" is H independent steps; its return G is the number of action-0 picks.
We want  E_pi[G] = 0.9 H  using only episodes generated by b.

  ordinary IS  (Eq. 2.14):  V_OIS = (1/n) sum_i rho_i G_i
  weighted IS  (Eq. 2.16):  V_WIS = sum_i rho_i G_i / sum_i rho_i
  with rho_i = prod_t pi(A_t)/b(A_t)  (the importance ratio of the whole episode).

Part (a): one step (H = 1), MSE vs number of samples n, compared with on-policy MC.
Part (b): fixed n, growing horizon H: relative RMSE, and Kish's effective sample size
          ESS = (sum rho)^2 / sum rho^2, against the theory E_b[rho^2] = (sum_a pi^2/b)^H.

Run:  python code/ch00_math_toolkit/importance_sampling.py [--quick]
"""
import argparse
import os
import time

import numpy as np

from plot_style import setup, C, GREY

FIG_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "figures")

PI = np.array([0.9, 0.1])   # target policy
B = np.array([0.5, 0.5])    # behaviour policy
F = np.array([1.0, 0.0])    # reward of each action
RATIO = PI / B              # per-step importance ratios (1.8, 0.2)
SECOND_MOMENT = float(np.sum(PI ** 2 / B))  # E_b[rho^2] for one step = 1.64


def sample_episodes(rng, reps, n, H):
    """reps independent batches of n episodes of length H under b.
    Returns per-episode returns G and importance ratios rho, both shape (reps, n)."""
    actions = (rng.random((reps, n, H)) >= B[0]).astype(np.int8)  # action 1 w.p. b(1)
    G = F[actions].sum(axis=2)
    # products of many ratios under/overflow quickly: accumulate in log space
    log_rho = np.log(RATIO)[actions].sum(axis=2)
    return G, np.exp(log_rho)


def ois_theory_rel_rmse(H, n):
    """Exact relative RMSE of OIS (it is unbiased, so RMSE = sqrt(Var/n)).
    Change of measure: E_b[rho^2 G^2] = E_b[rho^2] * E_q[G^2] where, step by step,
    q(a) = (pi(a)^2/b(a)) / sum_a' pi(a')^2/b(a'), so G ~ Binomial(H, q(0)) under q."""
    q0 = (PI[0] ** 2 / B[0]) / SECOND_MOMENT
    EqG2 = H * q0 * (1 - q0) + (H * q0) ** 2
    var1 = SECOND_MOMENT ** H * EqG2 - (0.9 * H) ** 2
    return np.sqrt(var1 / n) / (0.9 * H)


def ois(G, rho):
    return (rho * G).mean(axis=-1)


def wis(G, rho):
    den = rho.sum(axis=-1)
    num = (rho * G).sum(axis=-1)
    return np.where(den > 0, num / np.where(den > 0, den, 1.0), 0.0)  # 0/0 := 0 (S&B convention)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--quick", action="store_true", help="smoke test, no figures")
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()
    rng = np.random.default_rng(args.seed)
    reps = 400 if args.quick else 4000
    print(f"[importance_sampling] seed={args.seed} reps={reps} quick={args.quick}")
    print(f"  pi={PI}, b={B}, rewards={F}, per-step ratios={RATIO}, E_b[rho^2]={SECOND_MOMENT:.2f}")
    t0 = time.time()

    # ------------------------------------------------------------ (a) H = 1
    true_v = float(PI @ F)  # 0.9
    ns = np.array([1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024])
    if args.quick:
        ns = ns[:7]
    rows = []
    print("\n(a) One step: estimate E_pi[f] = 0.9 from n samples")
    print(f"  {'n':>5s} {'on-pol MSE':>11s} {'OIS bias':>9s} {'OIS MSE':>9s} {'WIS bias':>9s} {'WIS MSE':>9s}")
    for n in ns:
        G, rho = sample_episodes(rng, reps, n, 1)
        on_policy = (rng.random((reps, n)) < PI[0]).astype(float).mean(axis=1)
        v_o, v_w = ois(G, rho), wis(G, rho)
        row = dict(n=n, on=((on_policy - true_v) ** 2).mean(),
                   ois_bias=v_o.mean() - true_v, ois=((v_o - true_v) ** 2).mean(),
                   wis_bias=v_w.mean() - true_v, wis=((v_w - true_v) ** 2).mean())
        rows.append(row)
        print(f"  {n:5d} {row['on']:11.5f} {row['ois_bias']:9.4f} {row['ois']:9.5f} "
              f"{row['wis_bias']:9.4f} {row['wis']:9.5f}")
    print("  theory: on-policy var 0.09/n, OIS var 0.81/n, WIS asymptotic var 0.0324/n; WIS at n=1 has mean 0.5")

    # ------------------------------------------------------------ (b) horizon
    n_eps = 1000
    Hs = [1, 2, 4, 8, 16, 32] if args.quick else [1, 2, 4, 8, 16, 24, 32, 48, 64]
    reps_b = 100 if args.quick else 600
    hor = []
    print(f"\n(b) Horizon H, n = {n_eps} episodes per estimate, {reps_b} repetitions")
    print(f"  {'H':>3s} {'E_b[rho^2]':>11s} {'OIS relRMSE':>12s} {'(theory)':>9s} {'WIS relRMSE':>12s} {'ESS theory':>11s} "
          f"{'ESS median':>11s} {'true Var(rho)':>14s} {'median sample Var(rho)':>23s}")
    for H in Hs:
        G, rho = sample_episodes(rng, reps_b, n_eps, H)
        v_true = 0.9 * H
        rel_o = np.sqrt(((ois(G, rho) - v_true) ** 2).mean()) / v_true
        rel_w = np.sqrt(((wis(G, rho) - v_true) ** 2).mean()) / v_true
        ess = rho.sum(axis=1) ** 2 / (rho ** 2).sum(axis=1)
        m2 = SECOND_MOMENT ** H
        th_o = ois_theory_rel_rmse(H, n_eps)
        hor.append(dict(H=H, ois=rel_o, ois_th=th_o, wis=rel_w, ess=np.median(ess),
                        ess_lo=np.percentile(ess, 10), ess_hi=np.percentile(ess, 90), ess_th=n_eps / m2))
        print(f"  {H:3d} {m2:11.3g} {rel_o:12.4f} {th_o:9.3g} {rel_w:12.4f} {n_eps / m2:11.3g} {np.median(ess):11.3g} "
              f"{m2 - 1:14.3g} {np.median(rho.var(axis=1)):23.3g}")

    if not args.quick:
        plt = setup()
        fig, axes = plt.subplots(1, 3, figsize=(15, 4.5))
        ax = axes[0]
        nn = np.array([r["n"] for r in rows])
        ax.loglog(nn, [r["ois"] for r in rows], "o-", color=C[1], ms=5, label="ordinary IS")
        ax.loglog(nn, [r["wis"] for r in rows], "s--", color=C[0], ms=5, label="weighted IS")
        ax.loglog(nn, [r["on"] for r in rows], "^:", color=C[2], ms=5, label="on-policy MC (samples from π)")
        ax.loglog(nn, 0.81 / nn, color=GREY, lw=0.8)
        ax.loglog(nn, 0.0324 / nn, color=GREY, lw=0.8)
        ax.plot([], [], color=GREY, lw=0.8, label="theory 0.81/n and 0.0324/n")
        ax.set_title("(a) One step: MSE vs number of samples")
        ax.set_xlabel("samples n"); ax.set_ylabel("MSE"); ax.legend()

        ax = axes[1]
        HH = [h["H"] for h in hor]
        ax.semilogy(HH, [h["ois"] for h in hor], "o-", color=C[1], ms=5, label="ordinary IS")
        ax.semilogy(HH, [h["wis"] for h in hor], "s--", color=C[0], ms=5, label="weighted IS")
        ax.semilogy(HH, [h["ois_th"] for h in hor], ":", color=C[1], lw=1.5, label="ordinary IS, exact theory")
        ax.set_title(f"(b) Episodes of length H, n = {n_eps}")
        ax.set_xlabel("horizon H"); ax.set_ylabel("relative RMSE of estimate of E_π[G]"); ax.legend()

        ax = axes[2]
        ax.semilogy(HH, [h["ess"] for h in hor], "o-", color=C[0], ms=5, label="Kish ESS, median over batches")
        ax.fill_between(HH, [h["ess_lo"] for h in hor], [h["ess_hi"] for h in hor], color=C[0], alpha=0.15,
                        lw=0, label="10–90% range")
        ax.semilogy(HH, [h["ess_th"] for h in hor], "--", color=GREY, lw=1.2, label=r"$n\,/\,1.64^H$ (theory)")
        ax.set_ylim(1e-3, 3e3)
        ax.set_title(f"(c) Effective sample size out of n = {n_eps}")
        ax.set_xlabel("horizon H"); ax.set_ylabel("ESS"); ax.legend()
        fig.tight_layout()
        path = os.path.join(FIG_DIR, "importance_sampling.png")
        fig.savefig(path)
        print(f"\nsaved {path}")

    h_last = hor[-1]
    print(f"\nSummary: at n=1 WIS is biased (mean {rows[0]['wis_bias'] + 0.9:.3f} vs 0.9) but its MSE at "
          f"n={rows[-1]['n']} is {rows[-1]['ois'] / rows[-1]['wis']:.1f}x smaller than OIS; at H={h_last['H']} "
          f"the median ESS is {h_last['ess']:.3g} of {n_eps} episodes. runtime {time.time() - t0:.1f}s")


if __name__ == "__main__":
    main()
